Replace uuid-devel With libuuid-devel
Builds run with the present image fail with:

fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
          ^~~~~~~~~~~~~
compilation terminated.

Using the libuuid-devel package causes the builds to pass.